exemploDeIs = input('Digite algo: ')
print('Esse valor Digitado de {} para isalnum é {}'.format(exemploDeIs, exemploDeIs.isalnum()))
print('Esse valor Digitado de{} para isalpha é {}'.format(exemploDeIs, exemploDeIs.isalpha()))
print('Esse valor Digitado de{} para isascii é {}'.format(exemploDeIs, exemploDeIs.isascii()))
print('Esse valor Digitado de{} para isdigit é {}'.format(exemploDeIs, exemploDeIs.isdigit()))
print('Esse valor Digitado de{} para islower é {}'.format(exemploDeIs, exemploDeIs.islower()))
print('Esse valor Digitado de{} para isdecimal é {}'.format(exemploDeIs, exemploDeIs.isdecimal()))
print('Esse valor Digitado de{} para isidentifier é {}'.format(exemploDeIs, exemploDeIs.isidentifier()))
print('Esse valor Digitado de{} para isnumeric é {}'.format(exemploDeIs, exemploDeIs.isnumeric()))
print('Esse valor Digitado de{} para isprintable é {}'.format(exemploDeIs, exemploDeIs.isprintable()))
print('Esse valor Digitado de{} para isupper é {}'.format(exemploDeIs, exemploDeIs.isupper()))
print('Esse valor Digitado de{} para __init_subclass__ é {}'.format(exemploDeIs, exemploDeIs.__init_subclass__()))
print('Esse valor Digitado de{} para isspace é {}'.format(exemploDeIs, exemploDeIs.isspace()))

